config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { sessions: 'users/sessions' }

  post 'documents/create'
  get 'page/index'
  root to: 'page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies do
    collection do 
      get 'search'
    end
  end

  resources :users do
    collection do 
      get 'search'
    end
  end

  resources :quotations do
	  member do 
	    get 'preview'
      get 'status'
      get 'contract'
      get 'annexe'
      get 'notification'
      get 'edit_status'
	  end
    
    collection do 
      get 'search'
    end
	end

  resources :exams do
    collection do 
      get 'search'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]

  validates :login, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
  # validates :role_ids, presence: true
  has_many :companies
  attr_writer :login_user


  def login_user
    @login_user || self.login || self.email
  end

  def email_required?
	  false
	end

  def role_name
    if self.roles.first.present?
      if self.roles.first.name == "admin"
        "Administrador del Sistema"
      elsif self.roles.first.name == "approver"
        "Aprobador"
      elsif self.roles.first.name == "seller"
        "Comercial"
      end
    else
      "Sin Asignar"
    end
  end

	
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout "blank"
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :get_roles, only: [:new, :create, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    if !current_user.has_role? :admin
      role = Role.find_by_name("seller")
      @users = role.users
    end
    @users = @users.order(:name).page(params[:page]).per(20)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def search
    @users = User.all
    if !current_user.has_role? :admin
      role = Role.find_by_name("seller")
      @users = role.users
    end

    if params[:search] && params[:search][:q].present?
      @users = @users.where("name ILIKE ? OR email ILIKE ? ", "%#{params[:search][:q]}%", "%#{params[:search][:q]}%")
    end

    @users = @users.order(:name).page(params[:page]).per(20)
  end

  # GET /users/new
  def new
    @user = User.new
    @user.active = true
    respond_modal_with @user
  end

  # GET /users/1/edit
  def edit
    respond_modal_with @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.create(user_params)
    Rails.logger.info "===>>>>>>>: #{@user.errors.full_messages}"
    respond_modal_with @user, location: users_path
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user.update(user_params)
    respond_modal_with @user, location: users_path
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    # @user.destroy
    @user.active = false
    @user.save
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User correctamente desactivado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id, :email, :name, :login, :active, :photo, :signature, :encrypted_password, :password, :role_ids)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, remote: request.xhr?, html: { data: { modal: true } }) do |f| %>
  <div class="modal-body">
    <div class="row">
     
      <div class="col-md-6">
        <%= f.input :login %>    
      </div>

      <div class="col-md-6">
      	<div style="padding-bottom: 10px;position: relative;margin: 8px 0 0;">
      		<%= f.label user.new_record? ? "Nueva contraseña" : "Editar contraseña?" %>
	        <span class="change_password"><%= check_box_tag("change_password") %></span>
	        <% if user.new_record? %> 
		        <%= f.password_field :password, autocomplete: "off", :class => "form-control" %>
		      <% else %> 
		        <%= f.password_field :password, autocomplete: "off", :class => "form-control", :disabled => true %>
		      <% end %> 	
      	</div>
      	
      </div>


      <div class="col-md-12">
        <%= f.input :name %>    
      </div>

      <div class="col-md-12">
        <%= f.input :email %>
      </div>

      <% unless @user.role_ids.include?(1) %>
	      <div class="col-md-12">
	        <%= f.input :role_ids, collection: @all_roles, label_method: lambda { |p| "#{p.role_name}"}, prompt: "Seleccione opción", input_html: {class: 'select_2'} %>
	      </div>
	    <% end %>


			<div class="col-md-12">
        <%= f.input :active %>
      </div>

      <input type="hidden" name="url" id="url" value="">

     <!--  <div class="col-md-12">
        <%= f.input :photo %>
      </div> -->
    </div>

   

  </div>
    

  <div class="modal-footer">
    <div class="actions">
      <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
      <%= f.submit "Guardar", class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $('select.select_2').select2({
    language: {
      noResults: function () {
        return "No se encontró resultados";
      }
    },
    placeholder: function(){
      $(this).data('placeholder');
    },
    containerCssClass: ':all:',
    theme: "bootstrap",
    dropdownParent: $('#modal .modal-body')
  });

  $(".date-selector").flatpickr({
    enableTime: false,
    dateFormat: "Y-m-d",
  });

  $("#url").val(window.location.pathname);

  $("#change_password").click(function() {
	  if ($(this).is(":checked")){
	    $("#user_password").removeAttr("disabled");
	  }else{
	    $("#user_password").attr("disabled", "disabled");
	  }
	});
</script>

app/views/users/edit.html.erb
<div class="modal-header">
  <h5 class="modal-title">Editar Usuario</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <div class="card-header card-header-icon card-header-info">
        <div class="card-icon">
          <i class="material-icons">search</i>
          <span style="width: 20px;height: 33px;line-height: 33px;font-size: 20px;">Buscar Usuario</span>
        </div>
      </div>
      <div class="card-body">
        <%= simple_form_for :search, url: search_users_path, method: "GET", html: { class: 'search-content' } do |f| %>
          <%= f.input :q, label: "Nombre/correo" %>
          <%= f.submit "Buscar", :class => "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <h4 class="card-header card-header-info">Usuarios</h4>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table responsive">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Usuario</th>
                <th>Correo</th>
                <th>Rol</th>
                <th class="text-center">Activo</th>
                <th>Acciones</th>
              </tr>
            </thead>

            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <span>Nombre</span>
                    <%= user.name %>
                  </td>
                  <td>
                    <span>Usuario</span>
                    <%= user.login %>
                  </td>
                  <td>
                    <span>Correo</span>
                    <%= user.email %>
                  </td>
                  <td>
                    <span>Rol</span>
                    <%= user.role_name %>
                  </td>
                  <td class="text-center hide-small">
                    <span>Activo</span>
                    <%= user.active.present? ? "Si" : "No" %>
                  </td>
                  <td class="actions">
                    <span>Acciones</span>
                    <% if current_user.has_role?(:admin) || current_user.has_role?(:approver) %>
                      <%= link_to_show(user) %>
                      <%= link_to_edit(edit_user_path(user)) %>
                      <%= link_to_delete(user) %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <%= paginate @users %>
        <% if current_user.has_role?(:admin) || current_user.has_role?(:approver) %>
          <%= link_to "Nuevo".html_safe, new_user_path, :class => "btn btn-success", data: { modal: true }  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="modal-header">
  <h5 class="modal-title">Nuevo Usuario</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', user: @user %>

app/views/users/search.html.erb
<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <div class="card-header card-header-icon card-header-info">
        <div class="card-icon">
          <i class="material-icons">search</i>
          <span style="width: 20px;height: 33px;line-height: 33px;font-size: 20px;">Buscar Usuario</span>
        </div>
      </div>
      <div class="card-body">
        <%= simple_form_for :search, url: search_users_path, method: "GET", html: { class: 'search-content' } do |f| %>
          <%= f.input :q, label: "Nombre/correo", input_html: {value: params[:search][:q]} %>
          <%= f.submit "Buscar", :class => "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <h4 class="card-header card-header-info">Usuarios</h4>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table ">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Correo</th>
                <th>Rol</th>
                <th class="text-center">Activo</th>
                <th>Acciones</th>
              </tr>
            </thead>

            <tbody>
            	<% if @users.any? %>
	              <% @users.each do |user| %>
	                <tr>
	                  <td><%= user.name %></td>
	                  <td><%= user.email %></td>
	                  <td><%= user.role_name %></td>
	                  <td class="text-center"><%= user.active.present? ? "Si" : "No" %></td>
	                  <td>
                      <% if current_user.has_role?(:admin) || current_user.has_role?(:approver) %>
  	                    <%= link_to_show(user) %>
  	                    <%= link_to_edit(edit_user_path(user)) %>
  	                    <%= link_to_delete(user) %>
                      <% end %>
	                  </td>
	                </tr>
	              <% end %>
	            <% else %>
	            	<tr>
	            		<td colspan="5">
	            			No existen resultados
	            		</td>
	            	</tr>
	            <% end %>
            </tbody>
          </table>
        </div>
        <%= paginate @users %>
        <% if current_user.has_role?(:admin) || current_user.has_role?(:approver) %>
          <%= link_to "Nuevo".html_safe, new_user_path, :class => "btn btn-success", data: { modal: true }  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>