config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { sessions: 'users/sessions' }

  post 'documents/create'
  get 'page/index'
  root to: 'page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies do
    collection do 
      get 'search'
    end
  end

  resources :users do
    collection do 
      get 'search'
    end
  end

  resources :quotations do
	  member do 
	    get 'preview'
      get 'status'
      get 'contract'
      get 'annexe'
      get 'notification'
      get 'edit_status'
	  end
    
    collection do 
      get 'search'
    end
	end

  resources :exams do
    collection do 
      get 'search'
    end
  end
end

app/models/quotation.rb
class Quotation < ApplicationRecord
	
	validates :company_id, :presence => true

	validates :description, :presence => true
	# validates :total_users, :numericality => {:greater_than => 0}

	validates :addressed_to, :presence => true

	belongs_to :company
	accepts_nested_attributes_for :company


	has_many :quotation_items, foreign_key: "quotation_id", :dependent => :destroy
  has_many :exams, through: :quotation_items, source: :exam
  accepts_nested_attributes_for :quotation_items


  belongs_to :created_by, class_name: "User", foreign_key: "created_by_id"
  belongs_to :approved_user, class_name: "User", foreign_key: "approved_user_id", :optional => true
  belongs_to :rejected_user, class_name: "User", foreign_key: "rejected_user_id", :optional => true

  validates :exam_number, :numericality => { :greater_than => 0}


	has_many :quotation_contracts, foreign_key: "quotation_id", :dependent => :destroy
	accepts_nested_attributes_for :quotation_contracts, allow_destroy: true

	has_many :quotation_annexes, foreign_key: "quotation_id", :dependent => :destroy, class_name: "QuotationAnnexe"
	accepts_nested_attributes_for :quotation_annexes, allow_destroy: true

	has_many :quotation_columns, foreign_key: "quotation_id", :dependent => :destroy, class_name: "QuotationColumn"
	# accepts_nested_attributes_for :quotation_columns, allow_destroy: true, reject_if: proc { |att| att['title'].blank?
	accepts_nested_attributes_for :quotation_columns, allow_destroy: true

  # has_many :medical_profile_exams, foreign_key: "medical_profile_id", :dependent => :destroy
  # has_many :exams, through: :medical_profile_exams, source: :exam
  # accepts_nested_attributes_for :exams

	attr_accessor :step, :exam_number

	def saved_company?
		self.company_id.present? && self.company.valid?
	end

	def saved_quotation?
		quotation_items_valid = true
		quotation_items_valid = false if self.quotation_items.map{|q| q.valid?}.include?(false)
		self.description.present? && self.exam_number > 0 && quotation_items_valid
	end

	def saved_addressed?
		self.addressed_to.present?
	end
	
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  load_and_authorize_resource
  before_action :set_quotation, only: [:show, :edit, :update, :destroy, :preview, :status, :notification, :contract]
  before_action :get_companies, :get_users, :get_sectors, :get_exams, only: [:new, :create, :edit, :update, :search, :index]
  before_action :get_status, only: [:new, :create, :edit, :update, :show, :index, :search]
  before_action :get_exam_types, only: [:show, :preview]

  # GET /quotations
  # GET /quotations.json
  def index
    # @quotations = Quotation.all
    
    if !current_user.has_role? :admin
      @quotations = Quotation.where(:created_by_id => current_user.id)
    else
      @quotations = Quotation.all
    end

    @quotations = @quotations.order(created_at: :desc).page(params[:page]).per(20)

  end

  def search
    @quotations = Quotation.all
    if params[:search].present? && params[:search][:company_id].present?
      @quotations = @quotations.where(:company_id => params[:search][:company_id])
    end
    if params[:search].present? && params[:search][:user_id].present?
      @quotations = @quotations.where(:created_by_id => params[:search][:user_id])
    end
    if params[:search].present? && params[:search][:status].present?
      @quotations = @quotations.where(:status => params[:search][:status])
    end
    @quotations = @quotations.order(created_at: :desc).page(params[:page]).per(20)

  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show

    @exams_item = @quotation.quotation_items.map{|e|
      {
        description: e.exam.name,
        type: e.exam.exam_type_id,
        quantity: e.quantity,
        value_0: e.value_0,
        value_1: e.value_1,
        value_2: e.value_2,
        value_3: e.value_3,
        value_4: e.value_4,
        total: e.total  
      }
    }

    @exams_item = @exams_item.group_by { |d| d[:type] }

    @columns = @quotation.quotation_columns.map{|q| q.title}

    if params[:modal].present?
      @modal = true
      respond_modal_with @quotation
    else
      respond_to do |format|
        format.html {}
      end
    end
  end

  def preview

    @exams_item = @quotation.quotation_items.map{|e|
      {
        description: e.exam.name,
        type: e.exam.exam_type_id,
        quantity: e.quantity,
        value_0: e.value_0,
        value_1: e.value_1,
        value_2: e.value_2,
        value_3: e.value_3,
        value_4: e.value_4,
        total: e.total  
      }
    }

    @exams_item = @exams_item.group_by { |d| d[:type] }

    @columns = @quotation.quotation_columns.map{|q| q.title}

    respond_to do |format|
      format.html  { render layout: false }
      format.pdf do
        render pdf: @quotation.id.to_s, disable_links: true, show_as_html: false, lowquality: true, margin:  {top: 0, bottom: 0, left: 0, right: 0 }
      end
    end
  end

  def notification
    email_to_send = params[:notification][:email].present? ? params[:notification][:email].split(",") : nil
    body_to_send = params[:notification][:body].present? ? params[:notification][:body] : nil
    Rails.logger.info "===>>> email_to_send: #{email_to_send}"
    QuotationMailer.quotation_pdf(@quotation, email_to_send, body_to_send).deliver_now if Rails.env.production? || Rails.env.development?

    respond_to do |format|
      format.html {redirect_to quotation_path(@quotation), notice: 'Notificación enviada correctamente.'}
    end
  end

  def status
    if params[:commit].present? && params[:commit] == "Aprobar"
      @quotation.status = 2
      @msj = "Cotización para #{@quotation.company.name} aprobada."
    elsif params[:commit].present? && params[:commit] == "Rechazar"
      @quotation.status = 4
      @msj = "Cotización para #{@quotation.company.name} rechazada."
    else params[:status].to_i.present?
      @quotation.status = params[:status].to_i
      if params[:status].to_i == 2
        @msj = "Cotización para #{@quotation.company.name} aprobada."
      elsif params[:status].to_i == 4
        @msj = "Cotización para #{@quotation.company.name} rechazada."
      end
    end

    @quotation.note = params[:quotation][:note] if params[:quotation].present?

    if @quotation.status == 2
      @quotation.approved_user_id = current_user.id
      @quotation.approved_date = Time.now
      QuotationMailer.quotation_approved(@quotation).deliver if Rails.env.production?
    elsif @quotation.status == 4
      @quotation.rejected_user_id = current_user.id
      @quotation.rejected_date = Time.now
      QuotationMailer.quotation_rejected(@quotation).deliver if Rails.env.production?
    end

    @quotation.save(:validate => false)

    flash[:notice] = @msj
    Rails.logger.info "===>>>>>>>: #{@quotation.errors.full_messages}"
    @quotations_redirect = "/quotations/search?search[status]=1"
    respond_to do |format|
      format.js  {}
      format.html {redirect_to @quotations_redirect}
    end
  end

  def contract
    @quotation.exam_number = 1
    @quotation.update(quotation_params)
    respond_to do |format|
      format.js  {}
      format.html {redirect_to root_path}
    end
  end

  def annexe
    @quotation.exam_number = 1
    @quotation.update(quotation_params)
    respond_to do |format|
      format.js  {}
      format.html {redirect_to root_path}
    end
  end

  def edit_status
    @quotation.step = 3
    respond_modal_with @quotation
  end

  # GET /quotations/new
  def new
    @other_companies = @all_companies.where.not(:user_id => current_user.id).map{|c| c.ruc}
    @other_companies = @other_companies + current_user.companies.map{|c| c.ruc if c.in_quotation}
    @quotation = Quotation.new

    @archive = params[:archive].present? ? true : false
    # @quotation.exam_ids = [1, 2] unless @quotation.exam_ids.any?
    flash[:notice] = nil
    
    if params[:ci].present?
      company = Company.where(:ruc => params[:ci].to_s.strip).last
    end

    if company.present? && company.user_id == current_user.id
      # Si la empresa le pertenese
      @quotation.company_id = company.id
    elsif !company.present?
      # Si es una nueva empresa
      @quotation.company = Company.new
      @quotation.company.user_id = current_user.id  
      @quotation.company.active = true
      if params[:ci].present?
        @quotation.company.ruc = params[:ci]
        @quotation.company.valid?
        if @quotation.company.ci_passport && @quotation.company.ci_passport.any?

        else
          @quotation.company.save(:validate => false)
          @quotation.company_id = @quotation.company.id
        end

      end
    elsif company.present? && company.user_id != current_user.id
      # Ci de empresa invalido
      @quotation.company = Company.new
      flash[:notice] = "Empresa con RUC #{company.ruc} asignada a #{company.user.name} (#{company.user.email})"
    end

    @quotation.step = @archive.present? ? 0 : 1
    @quotation.exam_number = 0
    @quotation.date = Time.now.to_date
    @quotation.validity = (Time.now + 5.days).to_date
    @quotation.total_users = 1
    @quotation.total = 0
    @quotation.status = 0

    @quotation.quotation_items << QuotationItem.new unless @quotation.quotation_items.any?
    @quotation.quotation_columns << QuotationColumn.new(:title => "Valor")
    @quotation.quotation_columns << QuotationColumn.new(:title => "")
    @quotation.quotation_columns << QuotationColumn.new(:title => "")
    @quotation.quotation_columns << QuotationColumn.new(:title => "")
    @quotation.quotation_columns << QuotationColumn.new(:title => "")

    respond_modal_with @quotation
  end

  # GET /quotations/1/edit
  def edit
    @quotation.step = 3
    respond_modal_with @quotation
  end

  # POST /quotations
  # POST /quotations.json
  def create

    @other_companies = @all_companies.where.not(:user_id => current_user.id).map{|c| c.ruc}
    @quotation = Quotation.new(quotation_params)

    if @quotation.step.to_i == 0 && params[:finish].present?
      @archive = true
      @quotation.status = 3
      @quotation.created_by_id = current_user.id
      @quotation.exam_number = 1
      @quotation.approved_user_id = current_user.id
      @quotation.approved_date = Time.now
      @quotation.addressed_to = @quotation.company.name
      if @quotation.valid?
        @quotation.save
        location = quotation_path(@quotation)
      else
        location = quotations_path
      end

    else
      @quotation.step = 1
      @quotation.exam_number = 0

      if @quotation.saved_company?
        @quotation.step = 2
        num_no_exam = 0
        if quotation_params[:quotation_items_attributes].present?
          quotation_params[:quotation_items_attributes].to_h.map{|q| num_no_exam  += 1 if q[1][:exam_id] == '' }
          @quotation.exam_number = quotation_params[:quotation_items_attributes].to_h.count - num_no_exam
        end

      end

      if @quotation.saved_quotation?
        @quotation.step = 3
      end
      if @quotation.saved_addressed? && params[:finish].present?
        @quotation.step = 4
      end

      if params[:preview_1].present?
        @quotation.step = 1
      end

      if params[:preview_2].present?
        @quotation.step = 2
      end
      
      if @quotation.step == 4 && params[:finish].present?
        @quotation.status = 1
        @quotation.created_by_id = current_user.id
        @quotation.save
        location = quotation_path(@quotation)
      else
        @quotation.valid?
        location = quotations_path
      end
    end

    # @quotation = Quotation.create(quotation_params)

    QuotationMailer.new_quotation(@quotation).deliver if @quotation.valid? && Rails.env.production?

    Rails.logger.info "===>>>>>>>: #{@quotation.errors.inspect}"
    respond_modal_with @quotation, location: location
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    @quotation.update(quotation_params)
    respond_modal_with @quotation, location: quotations_path
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_quotation_item_fields.html.erb
<div class="q-item nested-fields well">
  <%- select_opts = options_from_collection_for_select(@all_exams, 'id', 'name') %>


  
  <%= f.collection_select(:exam_id, @all_exams, :id, :full_name, { :prompt => 'Selecione un examen'}, :class => "q-item-select select_2" ) %>

<div class="row">
	<div class="large-6 columns">
	  <div class="row">
	    <div class="large-8 columns">
	      <%= f.label :city_unit, "VU. por ciudad " %>
	    </div>
	    <div class="large-4 columns">
	      <%= f.text_field :city_unit, :class => 'city', :value => number_with_precision(f.object.city_unit,:precision => 2) || 0 %>
	    </div>
	  </div>

	  <div class="row">
	    <div class="large-8 columns">
	      <%= f.label :province_unit, "VU. por provicia " %>
	    </div>
	    <div class="large-4 columns">
	      <%= f.text_field :province_unit, :class => 'province', :value => number_with_precision(f.object.province_unit,:precision => 2) || 0 %>
	    </div>
	  </div>


	  <div class="row">
	    <div class="large-8 columns">
	      <%= f.label :m_units_unit, "VU. por unidades móviles " %>
	    </div>
	    <div class="large-4 columns">
	      <%= f.text_field :m_units_unit , :class => 'mobile' , :value => number_with_precision(f.object.m_units_unit,:precision => 2) || 0%>
	    </div>
	  </div>
	</div>
	<div class="large-6 columns">
	</div>
</div>

  <%= f.hidden_field :quotation_id, :value => @quotation.id %>
  <%= link_to_remove_association "Quitar examen", f %>
</div>

app/views/quotations/_search_box.html.erb
<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <div class="card-header card-header-icon card-header-rose">
        <div class="card-icon">
          <i class="material-icons">search</i>
          <span style="width: 33px;height: 33px;line-height: 33px;font-size: 28px;">Buscar Cotización</span>
        </div>
      </div>
      <div class="card-body">
        <%= simple_form_for :search, url: search_quotations_path, method: "GET", html: { class: 'search-content' } do |f| %>
          <div class="row">
            <div class="col-md-6">
              <%= f.input :company_id, collection: @all_companies, :selected => params[:search].present? ? params[:search][:company_id] : "", label_method: lambda { |p| "#{p.full_name}"}, :include_blank => "Todos", label: "RUC/CI - Nombre Empresa", required: false, input_html: {class: 'select_index_2'} %>
            </div>
            <div class="col-md-6">
              <%= f.input :user_id, collection: @all_users, :selected => params[:search].present? ? params[:search][:user_id] : "", label_method: lambda { |p| "#{p.name}"}, :include_blank => "Todos", label: "Comercial", required: false, input_html: {class: 'select_index_2'} %>
            </div>

            <div class="col-md-6">
              <%= f.input :status, collection: @status, :selected => params[:search].present? ? params[:search][:status] : "", :include_blank => "Todos", label: "Etapa", required: false, input_html: {class: 'select_index_2'} %>
            </div>


            <div class="col-md-12">
              <%= f.submit "Buscar", :class => "btn btn-success", :id => "search" %>
              <%= link_to '<i class="material-icons">add_circle</i >Nuevo'.html_safe, new_quotation_path, :class => "btn btn-success", data: { modal: true }  %>
            </div>
          </div>
          
          
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    console.log("=====>>>> on layout")
    $('select.select_index_2').select2({
      language: {
        noResults: function () {
          return "No se encontró resultados";
        }
      },
      placeholder: function(){
        $(this).data('placeholder');
      },
      containerCssClass: ':all:',
      theme: "bootstrap",
    });
    function load_timeline(){
      console.log("Load time line")
      $("#search").click();
    }
    $("#search_company_id, #search_user_id, #search_status").change(function() {
      load_timeline();    
    });
  });
</script>

app/views/quotations/annexe.js.erb
$("#saved_annexes").show();
setTimeout(function() { $("#saved_annexes").hide(); }, 3000);

app/views/quotations/contract.js.erb
$("#saved_documents").show();
setTimeout(function() { $("#saved_documents").hide(); }, 3000);

app/views/quotations/edit.html.erb
<div class="modal-header">
  <h5 class="modal-title">Editar Cotización</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', quotation: @quotation %>

app/views/quotations/index.html.erb
<%= render 'search_box' %>


<div class="row">
  <div class="col-md-8 ">
  </div>
  <div class="col-md-4" style="text-align: right;">
    <a class="nav-link hide-small" href="/quotations" style="float: right; background: #ccc">
      <i class="material-icons">list</i>
    </a>
    <a class="nav-link" href="/quotations/search" style="float: right;">
      <i class="material-icons">view_module</i>
    </a>
  </div>
</div>

<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <h4 class="card-header card-header-info">Cotizaciones</h4>
      <div class="card-body">
        <table class="table responsive">
          <thead>
            <tr>
              <th>Empresa</th>
              <th>Fecha</th>
              <th>Vigencia</th>
              <th>Creado por</th>
              <th>Etapa</th>
              <th>Acciones</th>
            </tr>
          </thead>

          <tbody>
            <% if @quotations.any? %>
              <% @quotations.each do |quotation| %>
                <tr>
                  <td><%= link_to quotation.company.present? ? quotation.company.full_name : "Sin Asignar", quotation  %></td>
                  <td><%= l(quotation.date, format: @date_format_words)  %></td>
                  <td><%= quotation.validity.present? ? l(quotation.validity, format: @date_format_words) : "N/A"%></td>
                  <td><%= quotation.company.present? ? quotation.company.user.name : "Sin Asignar" %></td>
                  <td><%= select_array(@status, quotation.status) %></td>

                  <td>
                    
                    <%= link_to_edit(edit_quotation_path(quotation)) %>




                    <% if quotation.status <= 1 %>
                      
                      <%= link_to '<i class="material-icons">check_box</i>'.html_safe , status_quotation_path(quotation, :status => 2), data: { confirm: 'Esta seguro de aprobar?' }, rel: "tooltip", title: "Aprobar", class: "btn btn-info" %>
                      
                      
                      <%= link_to '<i class="material-icons">cancel</i>'.html_safe , status_quotation_path(quotation, :status => 4), data: { confirm: 'Esta seguro de rechazar?' }, rel: "tooltip", title: "Rechazar", class: "btn btn-danger" %>
                      
                    <% end %>

                  </td>
                </tr>
              <% end %>
            <% else %>
              <tr>
                <td>
                  No se encontró registros
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @quotations %>
        <%= link_to "Nuevo".html_safe, new_quotation_path, :class => "btn btn-success", data: { modal: true }  %>
      </div>
    </div>
  </div>
</div>

app/views/quotations/preview.html.erb
<!doctype html>
<html>
  <head>
    <title>
      <%= "Cotización: #{@quotation.company.present? ? @quotation.company.name : 'Sin Asignar'}"%>
    </title>
    <meta charset='utf-8' />
    
    <style type="text/css">
      body {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
        background-color: #FAFAFA;
        font: 12pt "Tahoma";
      }
      .text-right{
        text-align: right;
      }
      .text-left{
        text-align: left;
      }
      .text-center{
        text-align: center;
      }
      * {
          box-sizing: border-box;
          -moz-box-sizing: border-box;
      }
      .body-text{
        position: absolute;
        top: 0;
        width: 210mm;
        padding: 80px 110px 80px 80px;
        font-size:14px;
        font-family: Arial;
      }
      p{
        text-align: justify;
      }
      .page {
          width: 210mm;
          min-height: 296mm;
          max-height: 296mm;
          height: 296mm;
          margin: 10mm auto;
          border: 1px #D3D3D3 solid;
          background: white;
          box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
          position: relative;
          overflow: hidden;
      }
      .subpage {
          padding: 1cm;
          border: 5px red solid;
          height: 257mm;
          outline: 2cm #FFEAEA solid;
      }
      
      @page {
          size: A4;
          margin: 0;
      }
      @media print {
          html, body {
              width: 210mm;
              height: 297mm;        
          }
          .page {
              margin: 0;
              border: initial;
              border-radius: initial;
              width: initial;
              min-height: initial;
              box-shadow: initial;
              background: initial;
              page-break-after: always;
          }
      }
      table{

      }
      td{
        padding: 5px 10px;
      }
      </style>
  </head>
  <body onload='number_pages'>
    <%= render(:partial => 'show_table', :formats => [:html])  %>
    
  </body>
</html>

app/views/quotations/search.html.erb
<%= render 'search_box' %>

<div class="row">
  <div class="col-md-8 ">
  </div>
  <div class="col-md-4" style="text-align: right;">
    <a class="nav-link hide-small" href="/quotations" style="float: right;">
      <i class="material-icons">list</i>
    </a>
    <a class="nav-link" href="/quotations/search" style="float: right; background: #ccc">
      <i class="material-icons">view_module</i>
    </a>
  </div>
</div>


<div class="row">
  <% if @quotations.any? %>
    <% @quotations.each do |quotation| %>
      <div class="col-md-4 col-lg-4">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title"><strong><%= quotation.company.present? ? quotation.company.name : "Sin asignar" %></strong></h4>
            <h6 class="card-subtitle mb-2 text-muted"><%= l(quotation.date, format: @date_format_words) %></h6>
            <h6 class="card-subtitle mb-2 text-muted">
              TOTAL (aprox): 
              <strong style="background-color: #4caf50;background-color: #4caf50; padding: 5px;color: white; border-radius: 3px;">$<%= quotation.total %></strong>
            </h6>
            <p class="card-text">

              <!-- Some quick example text to build on the card title and make up the bulk of the card's content. -->
              <strong>Creado por:</strong>
              <%= quotation.created_by.present? ? quotation.created_by.name : "Sin Asignar" %>
              <br/>
              <strong>Etapa:</strong>
              <%= select_array(@status, quotation.status) %>
              <br/>
              <strong>Dirigido a:</strong>
              <%= quotation.addressed_to %>
              <br/>
              <strong>Vigencia:</strong>
              <%= quotation.validity.present? ? l(quotation.validity, format: @date_format_words) : "N/A" %>
              
              
            </p>

            <div class="row">
              <% if current_user.id == quotation.created_by_id || current_user.has_role?(:admin) || current_user.has_role?(:approver) %>
                <div class="col-lg-12 col-md-12 ml-auto mr-auto">
                  <%= link_to "<i class='material-icons'>print</i> Imprimir".html_safe, preview_quotation_path(quotation), :class => "btn btn-success", :style => "width: 100%", :target => "_blank" %>  
                </div>
              <% end %>
              <div class="col-lg-12 col-md-12 ml-auto mr-auto">
                <%= link_to "<i class='material-icons'>list_alt</i> Ver".html_safe, quotation_path(quotation, :modal => true), :class => "btn btn-info", :style => "width: 100%", data: { modal: true } %>  
              </div>

              <% if quotation.status <= 1 && (current_user.has_role?(:admin) || current_user.has_role?(:approver)) %>
                <div class="col-lg-6 col-md-6 ml-auto mr-auto">
                  <%= link_to '<i class="material-icons">check_box</i>'.html_safe , status_quotation_path(quotation, :status => 2), data: { confirm: 'Esta seguro de aprobar?' }, rel: "tooltip", title: "Aprobar", class: "btn btn-info", :style => "width: 100%" %>
                </div>
                <div class="col-lg-6 col-md-6 ml-auto mr-auto">
                  <%= link_to '<i class="material-icons">cancel</i>'.html_safe , status_quotation_path(quotation, :status => 4), data: { confirm: 'Esta seguro de rechazar?' }, rel: "tooltip", title: "Rechazar", class: "btn btn-danger", :style => "width: 100%" %>

                </div>
              <% else %>
                <div class="col-lg-12 col-md-12 ml-auto mr-auto">
                  <% if quotation.status == 1 %>
                    <div class="alert alert-success" role="alert" style="padding: 10px;margin-top: 5px;margin-bottom: 5px;text-align: center;font-size: 15px;text-transform: uppercase;font-weight: bolder;color: #00bcd4; border: 1px solid #00bcd4; background: transparent; ">
                      Pendiente
                    </div>
                  <% elsif quotation.status == 2 %>
                    <div class="alert alert-success" role="alert" style="padding: 10px;margin-top: 5px;margin-bottom: 5px;text-align: center;font-size: 15px;text-transform: uppercase;font-weight: bolder;color: #4caf50; border: 1px solid #4caf50; background: transparent; ">
                      Aprobado
                    </div>
                  <% elsif quotation.status == 3 %>
                    <div class="alert alert-danger" role="alert" style="padding: 10px;margin-top: 5px;margin-bottom: 5px;text-align: center;font-size: 15px;text-transform: uppercase;font-weight: bolder;color: #f55145; border: 1px solid #f55145; background: transparent;">
                      Finalizado
                    </div>
                  <% elsif quotation.status == 4 %>
                    <div class="alert alert-danger" role="alert" style="padding: 10px;margin-top: 5px;margin-bottom: 5px;text-align: center;font-size: 15px;text-transform: uppercase;font-weight: bolder;color: #f55145; border: 1px solid #f55145; background: transparent;">
                      Rechazado
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="col-md-12 col-lg-12">
      <p class="h2">
        No se encontró registros
      </p>
    </div>
  <% end %>
  
</div>

app/views/quotations/status.js.erb
<%- flash[:notice] = @msj %>
window.location.href = "<%= @quotations_redirect %>";