config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { sessions: 'users/sessions' }

  post 'documents/create'
  get 'page/index'
  root to: 'page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies do
    collection do 
      get 'search'
    end
  end

  resources :users do
    collection do 
      get 'search'
    end
  end

  resources :quotations do
	  member do 
	    get 'preview'
      get 'status'
      get 'contract'
      get 'annexe'
      get 'notification'
      get 'edit_status'
	  end
    
    collection do 
      get 'search'
    end
	end

  resources :exams do
    collection do 
      get 'search'
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
	validates :name, :presence => true
	validates_uniqueness_of :name, :message => '%{value} ya fue registrado en el sistema'
	validates :ruc, :presence => true
	validates_uniqueness_of :ruc, :message => '%{value} ya fue registrado en el sistema'
	validates :user_id, :presence => true
	validate :ci_passport
	belongs_to :user

	has_many :quotations

	after_save :save_full_name 

	def save_full_name
		if self.user_id && self.user_id > 0
			new_full_name = "#{self.ruc} #{self.name} (#{self.user.name}) #{self.in_quotation.present? ? "*" : ""}"
		else
			new_full_name = "#{self.ruc} #{self.name} (Sin Asignar) #{self.in_quotation.present? ? "*" : ""}"
    end
    Company.skip_callback :save, :after, :save_full_name
    self.update_attribute(:full_name, new_full_name)
    Company.set_callback :save, :after, :save_full_name
  end

  def in_quotation
  	if self.quotations.any? && self.quotations.last.status <= 1
  		true
  	else
  		false
  	end
  end

  

  def ci_passport
		require "id_ecuador"
		if new_record?
			ci = self.ruc
			if ci.present?
				# Passport validation
				cedula = IdEcuador.new ci
				if !cedula.valid? || !ci.scan(/\D/).empty?
					errors_mjs = ci.scan(/\D/).empty? ? cedula.errors.join(", ") : "Solo se acepta valores numéricos"
					errors.add(:ruc, "(#{ci}) #{errors_mjs}")
				end
			end
		end
	end

	
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :get_users, only: [:new, :create, :edit, :update]
  before_action :get_sectors, only: [:new, :create, :edit, :update, :show, :index, :search]
  respond_to :html

  # GET /companies
  # GET /companies.json
  def index
    # @companies = Company.all
    @companies = Company.all
    if !current_user.has_role?(:admin) && !current_user.has_role?(:approver)
      @companies = @companies.where(:user_id => current_user.id)
    end

    @companies = @companies.order(:name).page(params[:page]).per(20)
  end

  def search
    if params[:search] && params[:search][:q].present?
      @companies = Company.where("name ILIKE ? OR ruc ILIKE ? ", "%#{params[:search][:q]}%", "%#{params[:search][:q]}%")
    else
      @companies = Company.all
    end
    @companies = @companies.order(:name).page(params[:page]).per(20)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company.user_id = current_user.id
    @company.active = true
    respond_modal_with @company
  end

  # GET /companies/1/edit
  def edit
    respond_modal_with @company
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.create(company_params)

    @company_registered_by_ci = Company.where(ruc: company_params[:ruc]).last
    @company_registered_by_name = Company.where(name: company_params[:name]).last
    respond_modal_with @company, location: companies_path
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @company.update(company_params)
    respond_modal_with @company, location: companies_path
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    # @company.destroy
    @company.active = false
    @company.save
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Empresa desactivada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :ruc, :active, :direction, :sector, :contact_name, :contact_email, :contact_phone, :doctor_name, :doctor_email, :doctor_phone, :billing_name, :billing_email, :billing_phone, :user_id, :description)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company, remote: request.xhr?, html: { data: { modal: true } }) do |f| %>
  <div class="modal-body">
    <div class="row">
      <div class="col-md-12 ml-auto mr-auto">
        <h6 class="text-muted">Información de la empressa</h6>
        <hr/>
      </div>

      <div class="col-md-6 ml-auto mr-auto">
        <%= f.input :ruc %>
        <% if @company_registered_by_ci.present? %>
          <div class="invalid-feedback">
            Usuario: <%= @company_registered_by_ci.user.name %>
          </div>
          <div class="invalid-feedback">
            Email: <%= @company_registered_by_ci.user.email %>
          </div>
        <% end %>
      </div>

      <div class="col-md-6 ml-auto mr-auto">
        <%= f.input :name %>
        <% if @company_registered_by_name.present? %>
          <div class="invalid-feedback">
            Usuario: <%= @company_registered_by_name.user.name %>
          </div>
          <div class="invalid-feedback">
            Email: <%= @company_registered_by_name.user.email %>
          </div>
        <% end %>
      </div>

      <div class="col-md-6 ml-auto mr-auto">
        <%= f.input :sector, collection: @sectors, prompt: "Seleccione opción", input_html: {class: 'select_2'} %>
        
      </div>

      <div class="col-md-6 ml-auto mr-auto">
        <% if true %>
          <%= f.input :user_id, collection: @all_users, prompt: "Seleccione opción", input_html: {class: 'select_2'} %>
        <% else %>
          <div class="form-group email optional company_contact_email">
            <label class="string required" for="company_user">Asignado <abbr title="required">*</abbr></label>
            <p class="h4"><%= current_user.name %>  </p>
          </div>

          <%= f.input :user_id, as: :hidden, input_html: {value: current_user.id} %>
        <% end %>
      </div>

      <div class="col-md-12 ml-auto mr-auto">
        <h6 class="text-muted">Información de contacto</h6>
        <hr/>
      </div>

      <div class="col-md-4 ml-auto mr-auto">
        <%= f.input :contact_name %>
      </div>

      <div class="col-md-4 ml-auto mr-auto">
        <%= f.input :contact_email %>
      </div>

      <div class="col-md-4 ml-auto mr-auto">
        <%= f.input :contact_phone %>
      </div>

      <div class="col-md-4 ml-auto mr-auto">
        <%= f.input :doctor_name %>
      </div>

      <div class="col-md-4 ml-auto mr-auto">
        <%= f.input :doctor_email %>
      </div>

      <div class="col-md-4 ml-auto mr-auto">
        <%= f.input :doctor_phone %>
      </div>

      <div class="col-md-4 ml-auto mr-auto">
        <%= f.input :billing_name %>
      </div>

      <div class="col-md-4 ml-auto mr-auto">
        <%= f.input :billing_email %>
      </div>

      <div class="col-md-4 ml-auto mr-auto">
        <%= f.input :billing_phone %>
      </div>

      <div class="col-md-12 ml-auto mr-auto">
        <%= f.input :direction %>
      </div>

      <div class="col-md-12 ml-auto mr-auto">
        <%= f.input :description %>
      </div>
      <div class="col-md-12 ml-auto mr-auto">
        <%= f.input :active %>
      </div>
    </div>
  </div>

  <div class="modal-footer">

    <div class="actions">
      <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
      <%= f.submit "Guardar", class: "btn btn-info" %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $( document ).ready(function() {
    $('select.select_2').select2({
      language: {
        noResults: function () {
          return "No se encontró resultados";
        }
      },
      placeholder: function(){
        $(this).data('placeholder');
      },
      containerCssClass: ':all:',
      theme: "bootstrap",
      dropdownParent: $('#modal .modal-body')
    });
  });
</script>

app/views/companies/edit.html.erb
<div class="modal-header">
  <h5 class="modal-title">Editar Empresa</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', company: @company %>

app/views/companies/index.html.erb
<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <div class="card-header card-header-icon card-header-info">
        <div class="card-icon">
          <i class="material-icons">search</i>
          <span style="width: 20px;height: 33px;line-height: 33px;font-size: 20px;">Buscar Empresa</span>
        </div>
      </div>
      <div class="card-body">
        <%= simple_form_for :search, url: search_companies_path, method: "GET", html: { class: 'search-content' } do |f| %>
          <%= f.input :q, label: "Nombre/RUC" %>
          <%= f.submit "Buscar", :class => "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <h4 class="card-header card-header-info">Empresas</h4>
      <div class="card-body">
        <table class="table responsive">
          <thead>
            <tr>
              <th>RUC/CI</th>
              <th>Nombre</th>
              <th>Asignado</th>
              <th>Sector</th>
              <th>N. Contacto</th>
              <th>E. Contacto</th>
              <th>Activo</th>
              <th>Acciones</th>
            </tr>
          </thead>

          <tbody>
            <% if @companies.any? %>
              <% @companies.each do |company| %>
                <tr>
                  <td>
                    <span>RUC/CI</span>
                    <%= link_to company.ruc, company %>
                  </td>
                  <td>
                    <span>Nombre</span>
                    <%= company.name %>
                  </td>
                  <td>
                    <span>Asignado</span>
                    <%= company.user.present? ? company.user.name : "Sin Asignar" %>
                  </td>
                  <td>
                    <span>Sector</span>
                    <%= select_array(@sectors, company.sector) %>
                  </td>
                  <td>
                    <span>N. Contacto</span>
                    <%= company.contact_name %>
                  </td>
                  <td>
                    <span>E. Contacto</span>
                    <%= company.contact_email %>
                  </td>
                  <td class="hide-small">
                    <span>Activo</span>
                    <%= company.active.present? ? "Si" : "No" %>
                  </td>
                  <td class="actions">
                    <span>Acciones</span>
                    <%= link_to '<i class="material-icons">history</i>'.html_safe , search_quotations_path(:"search[company_id]" => company.id), rel: "tooltip", title: "Historial", class: "btn btn-info" %>
                      <%= link_to_edit(edit_company_path(company)) %>
                    <% if (current_user.has_role?(:seller) && company.user_id == current_user.id) || current_user.has_role?(:approver) || current_user.has_role?(:admin) %>
                      <%= link_to_delete(company) %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% else %>
              <tr>
                <td colspan="8">
                  No se encontro registros
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @companies %>
        <%= link_to 'Nuevo', new_company_path, :class => "btn btn-success", data: { modal: true }  %>
      </div>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<div class="modal-header">
  <h5 class="modal-title">Nueva Empresa</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', company: @company %>

app/views/companies/search.html.erb
<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <div class="card-header card-header-icon card-header-info">
        <div class="card-icon">
          <i class="material-icons">search</i>
          <span style="width: 20px;height: 33px;line-height: 33px;font-size: 20px;">Buscar Empresa</span>
        </div>
      </div>
      <div class="card-body">
        <%= simple_form_for :search, url: search_companies_path, method: "GET", html: { class: 'search-content' } do |f| %>
          <%= f.input :q, label: "Nombre/RUC", input_html: {value: params[:search][:q]} %>
          <%= f.submit "Buscar", :class => "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <h4 class="card-header card-header-info">Empresas</h4>
      <div class="card-body">
        <table class="table">
          <thead>
            <tr>
              <th>RUC/CI</th>
              <th>Nombre</th>
              <th>Asignado</th>
              <th>Sector</th>
              <th>N. Contacto</th>
              <th>E. Contacto</th>
              <th>Activo</th>
              <th>Acciones</th>
            </tr>
          </thead>

          <tbody>
            <% if @companies.any? %>
              <% @companies.each do |company| %>
                <tr>
                  <td><%= company.ruc %></td>
                  <td><%= company.name %></td>
                  <td><%= company.user.present? ? company.user.name : "Sin Asignar" %></td>
                  <td><%= select_array(@sectors, company.sector) %></td>
                  <td><%= company.contact_name %></td>
                  <td><%= company.contact_email %></td>
                  <td><%= company.active.present? ? "Si" : "No" %></td>
                  <td>

                    <%= link_to '<i class="material-icons">history</i>'.html_safe , search_quotations_path(:"search[company_id]" => company.id), rel: "tooltip", title: "Historial", class: "btn btn-info" %>
                    
                    
                      <%= link_to_edit(edit_company_path(company)) %>
                    <% if (current_user.has_role?(:seller) && company.user_id == current_user.id) || current_user.has_role?(:approver) || current_user.has_role?(:admin) %>
                      <%= link_to_delete(company) %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% else %>
              <tr>
                <td colspan="8">
                  No se encontro registros
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @companies %>
        <%= link_to 'Nuevo', new_company_path, :class => "btn btn-success", data: { modal: true }  %>
      </div>
    </div>
  </div>
</div>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Ruc:</strong>
  <%= @company.ruc %>
</p>

<p>
  <strong>Active:</strong>
  <%= @company.active %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @company.direction %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @company.sector %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @company.contact_name %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @company.contact_email %>
</p>

<p>
  <strong>Doctor name:</strong>
  <%= @company.doctor_name %>
</p>

<p>
  <strong>Doctor email:</strong>
  <%= @company.doctor_email %>
</p>

<p>
  <strong>Billing name:</strong>
  <%= @company.billing_name %>
</p>

<p>
  <strong>Billing email:</strong>
  <%= @company.billing_email %>
</p>

<p>
  <strong>User:</strong>
  <%= @company.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>