config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { sessions: 'users/sessions' }

  post 'documents/create'
  get 'page/index'
  root to: 'page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies do
    collection do 
      get 'search'
    end
  end

  resources :users do
    collection do 
      get 'search'
    end
  end

  resources :quotations do
	  member do 
	    get 'preview'
      get 'status'
      get 'contract'
      get 'annexe'
      get 'notification'
      get 'edit_status'
	  end
    
    collection do 
      get 'search'
    end
	end

  resources :exams do
    collection do 
      get 'search'
    end
  end
end

app/models/exam.rb
class Exam < ApplicationRecord
	validates :name, presence: true, uniqueness: true
  validates :code, presence: true, uniqueness: true

  has_many :exam_descriptions, foreign_key: "exam_id", :dependent => :destroy
  accepts_nested_attributes_for :exam_descriptions
  def full_name
    "#{self.code} #{self.name}"
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_action :get_exam_types, only: [:edit, :update, :create, :new, :index]

  # GET /exams
  # GET /exams.json
  def index
    # @exams = Exam.all
    @exams = Exam.order(:name).page(params[:page]).per(20)
  end

  def search
    if params[:search] && params[:search][:q].present?
      @exams = Exam.where("name ILIKE ? OR code ILIKE ? ", "%#{params[:search][:q]}%", "%#{params[:search][:q]}%")
    else
      @exams = Exam.all
    end
    @exams = @exams.order(:name).page(params[:page]).per(20)
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
    respond_modal_with @exam
  end

  # GET /exams/1/edit
  def edit
    respond_modal_with @exam
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.create(exam_params)
    flash[:notice] = 'Exámen creado correctamente.'
    respond_modal_with @exam, location: exams_path
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    @exam.update(exam_params)
    flash[:notice] = 'Exámen actualizado correctamente.'
    respond_modal_with @exam, location: exams_path
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    # @exam.destroy
    @exam.active = false
    @exam.save
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exámen desactivado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:name, :code, :active, :description, :exam_type_id, 
        exam_descriptions_attributes: [:id, :exam_id, :name, :active, :_destroy])
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= simple_nested_form_for(@exam, remote: request.xhr?, html: { data: { modal: true } }) do |f| %>
  <div class="modal-body">
    <div class="row">
      <div class="col-md-6 ml-auto mr-auto">
        <%= f.input :code %>
      </div>

      <div class="col-md-6 ml-auto mr-auto">
        <%= f.input :name %>
      </div>

      <div class="col-md-12 ml-auto mr-auto">
        <!-- <%= f.input :description %> -->
        <%= f.input :exam_type_id, collection: @exam_types, prompt: "Seleccione opción", input_html: {class: 'select_2'} %>
      </div>

      <div class="col-md-12 ml-auto mr-auto">
        <label class="text required" for="quotation_description">Descripción <abbr title="required">*</abbr></label>
      </div>

      <div class="col-md-12 ml-auto mr-auto" id="row_items">
        <%= f.fields_for :exam_descriptions, @exam.exam_descriptions.sort_by(&:id) , :wrapper => false do |description_form| %>
          <div class="row fields">
            
            <div class="col-md-10">
              <%= description_form.input :name, label: false %>
            </div>

            <!-- <div class="col-md-2">
              <%= description_form.input :active, label: false %>
            </div> -->

            <div class="col-md-2">
              <%= description_form.link_to_remove "<i class='material-icons'>delete</i>".html_safe, :class => "btn btn-danger" %>
            </div>
          </div>          
        <% end %>
      </div>

      <div class="col-md-12 ml-auto mr-auto">
        <%= f.link_to_add "<i class='material-icons'>add_circle</i> Añadir".html_safe, :exam_descriptions, :data => { :target => "#row_items" }, :class => "btn btn-info", :style => "text-align: right" %>
      </div>

      <div class="col-md-12 ml-auto mr-auto">
        <%= f.input :active %>
      </div>

    </div>
  </div>


  <div class="modal-footer">
    <div class="actions">
      <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
      <%= f.submit "Guardar", class: "btn btn-info" %>
    </div>
  </div>
  
<% end %>
<script type="text/javascript">
  $('select.select_2').select2({
    language: {
      noResults: function () {
        return "No se encontró resultados";
      }
    },
    placeholder: function(){
      $(this).data('placeholder');
    },
    containerCssClass: ':all:',
    theme: "bootstrap",
    dropdownParent: $('#modal .modal-body')
  });

  $(".date-selector").flatpickr({
    enableTime: false,
    dateFormat: "Y-m-d",
  });

</script>

app/views/exams/edit.html.erb
<div class="modal-header">
  <h5 class="modal-title">Editar Examen</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', exam: @exam %>

app/views/exams/index.html.erb
<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <div class="card-header card-header-icon card-header-info">
        <div class="card-icon">
          <i class="material-icons">search</i>
          <span style="width: 20px;height: 33px;line-height: 33px;font-size: 20px;">Buscar Exámen</span>
        </div>
      </div>
      <div class="card-body">
        <%= simple_form_for :search, url: search_exams_path, method: "GET", html: { class: 'search-content' } do |f| %>
          <%= f.input :q, label: "Nombre/Código", input_html: {value: params[:search].present? ? params[:search][:q] : "" } %>
          <%= f.submit "Buscar", :class => "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <h4 class="card-header card-header-info">Exámenes</h4>
      <div class="card-body">
        
        <table class="table responsive">
          <thead>
            <tr>
              <th class="text-center">Código</th>
              <th>Nombre</th>
              <th class="text-center">Activo</th>
              <th>Tipo Examen</th>
              <th>Acciones</th>
            </tr>
          </thead>

          <tbody>
            <% @exams.each do |exam| %>
              <tr>
                <td class="text-center">
                  <span>Código</span>
                  <%= exam.code %>    
                </td>
                <td>
                  <span>Nombre</span>
                  <%= exam.name %>
                </td>
                <td class="text-center ">
                  <span>Activo</span>
                  <%= exam.active.present? ? "Si" : "No" %>
                </td>
                <td>
                  <span>Tipo Examen</span>
                  <%= select_array(@exam_types, exam.exam_type_id) %>
                </td>
                <td class="actions">
                  <span>Acciones</span>
                  <%= link_to_show(exam) %>
                  <%= link_to_edit(edit_exam_path(exam)) %>
                  <%= link_to_delete(exam) %>
                  
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @exams %>
        <%= link_to "Nuevo".html_safe, new_exam_path, :class => "btn btn-success", data: { modal: true }  %>
      </div>
    </div>
  </div>
</div>

app/views/exams/new.html.erb
<div class="modal-header">
  <h5 class="modal-title">Nuevo Examen</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', exam: @exam %>

app/views/exams/search.html.erb
<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <div class="card-header card-header-icon card-header-info">
        <div class="card-icon">
          <i class="material-icons">search</i>
          <span style="width: 20px;height: 33px;line-height: 33px;font-size: 20px;">Buscar Exámen</span>
        </div>
      </div>
      <div class="card-body">
        <%= simple_form_for :search, url: search_exams_path, method: "GET", html: { class: 'search-content' } do |f| %>
          <%= f.input :q, label: "Nombre/Código", input_html: {value: params[:search].present? ? params[:search][:q] : "" } %>
          <%= f.submit "Buscar", :class => "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 ml-auto mr-auto">
    <div class="card">
      <h4 class="card-header card-header-info">Exámenes</h4>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table ">
            <thead>
              <tr>
                <th class="text-center">Código</th>
                <th>Nombre</th>
                <th class="text-center">Activo</th>
                <th>Descripción</th>
                <th>Acciones</th>
              </tr>
            </thead>

            <tbody>
              <% @exams.each do |exam| %>
                <tr>
                  <td class="text-center"><%= exam.code %></td>
                  <td><%= exam.name %></td>
                  <td class="text-center"><%= exam.active.present? ? "Si" : "No" %></td>
                  <td><%= exam.description %></td>
                  <td>
                    <%= link_to_show(exam) %>
                    <%= link_to_edit(edit_exam_path(exam)) %>
                    <%= link_to_delete(exam) %>
                    
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <%= paginate @exams %>
        <%= link_to "Nuevo".html_safe, new_exam_path, :class => "btn btn-success", data: { modal: true }  %>
      </div>
    </div>
  </div>
</div>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exam.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @exam.code %>
</p>

<p>
  <strong>Active:</strong>
  <%= @exam.active %>
</p>

<p>
  <strong>Description:</strong>
  <%= @exam.description %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>